openapi: 3.0.3
info:
  title: FSC Properties
  version: 1.0.0
  description: Properties REST API
paths: {}
components:
  schemas:
    properties:
      type: object
      description: A flexible object to hold additional grant properties
      additionalProperties: true
      example:
        max_requests_per_minute: 100
        tags: ["api", "v1", "beta"]
        custom_metadata:
          department: "IT"
          project: "FSC Integration"
